name: Extract APIs from Swagger

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment for the build (e.g., dev, qa, prod)'
        required: true
        type: string

jobs:
  extract-apis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          pwd  # Print current working directory
          ls -R  # List all files recursively

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Verify .NET SDK version
        run: |
          dotnet --version

      - name: Restore and build the .NET project
        run: |
          if [ ! -f "MyAPI/MyApi.csproj" ]; then
            echo "Error: MyAPI/MyApi.csproj not found!"
            exit 1
          fi
          dotnet restore MyAPI/MyApi.csproj
          dotnet build MyAPI/MyApi.csproj --no-restore --configuration Release --output ./bin/Release/net8.0
        env:
          DOTNET_ROOT: /usr/share/dotnet

      - name: Install Swashbuckle CLI tool
        run: |
          dotnet tool install --global Swashbuckle.AspNetCore.Cli --version 6.2.3 || echo "Installation failed"
          # Verify the tool is installed
          dotnet tool list --global
          # Check the tools directory
          ls -la $HOME/.dotnet/tools

      - name: Extract Swagger JSON from DLL
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          # Verify PATH
          echo "PATH is: $PATH"
          # Verify the dotnet swagger command is available
          which dotnet-swagger || echo "dotnet-swagger not found"
          dotnet swagger tofile --output swagger.json ./bin/Release/net8.0/MyApi.dll v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Split Swagger JSON into YAML files
        run: |
          python -c '
          import json
          import yaml
          import os
          import sys

          # Read environment from input
          environment = "${{ inputs.environment }}"

          # Load Swagger JSON from file
          with open("swagger.json", "r") as f:
              swagger_json = json.load(f)

          # Create output directory
          output_dir = f"output/{environment}"
          os.makedirs(output_dir, exist_ok=True)

          # Split API paths into separate YAML files
          for path, details in swagger_json["paths"].items():
              yaml_data = {"paths": {path: details}}
              filename = os.path.join(output_dir, f"{path.strip('/').replace('/', '-')}.yaml")
              with open(filename, "w") as file:
                  yaml.dump(yaml_data, file)
          '

      - name: Upload API YAML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-yaml-files-${{ inputs.environment }}
          path: output/${{ inputs.environment }}/*.yaml
